#!/bin/sh

# Register with gnome-session so that it does not kill the whole session thinking it is dead.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.RegisterClient "string:i3-gnome" "string:$DESKTOP_AUTOSTART_ID"
fi

REGOLITH_I3_CONFIG_DIR="$HOME/.config/i3-regolith"

# Initialize Regolith session
/bin/bash /usr/bin/regolith-config-init.sh

# Launch i3wm with the Regolith configuration
i3 -c $REGOLITH_I3_CONFIG_FILE

# Close session when i3 exits.
if [ -n "$DESKTOP_AUTOSTART_ID" ]; then
	dbus-send --print-reply --session --dest=org.gnome.SessionManager "/org/gnome/SessionManager" org.gnome.SessionManager.Logout "uint32:1"
fi
