#!/bin/sh

if [ -z $XDG_CURRENT_DESKTOP ]; then
    export XDG_CURRENT_DESKTOP="GNOME-Flashback:GNOME"
fi

# gnome-session broke compatability between 18.04 and 19.x version.
UBUNTU_VERSION=$(lsb_release -rs)
if [ "$UBUNTU_VERSION" = "18.04" ]; then
    GNOME_PARAM=""
else
    GNOME_PARAM="--builtin"
fi

exec gnome-session $GNOME_PARAM --session=i3-gnome-flashback --disable-acceleration-check "$@"
